# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=250)),
                ('impresion_general', models.CharField(max_length=250)),
                ('aroma', models.CharField(max_length=250)),
                ('apariencia', models.CharField(max_length=250)),
                ('sabor', models.CharField(max_length=250)),
                ('sensacion', models.CharField(max_length=250)),
                ('ingredientes', models.CharField(max_length=250)),
                ('comentarios', models.CharField(max_length=250)),
                ('comparacion', models.CharField(max_length=250)),
                ('historia', models.CharField(max_length=250)),
                ('estadisticas', models.CharField(max_length=250)),
                ('ejemplos', models.CharField(max_length=250)),
                ('etiquetas', models.CharField(max_length=250)),
            ],
        ),
    ]
