# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='apariencia',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='aroma',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='comentarios',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='comparacion',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='ejemplos',
            field=models.CharField(max_length=2050),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='estadisticas',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='etiquetas',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='historia',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='impresion_general',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='ingredientes',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sabor',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sensacion',
            field=models.CharField(max_length=2500),
        ),
    ]
